-- creating a database
-- CREATE DATABASE RGM;

-- creating students table
-- CREATE TABLE STUDENT (
-- 	STUDENT_ID INT PRIMARY KEY NOT NULL,
--    STUDENT_NAME VARCHAR(30) NOT NULL,
--    STUDENT_CONTACT INT NOT NULL,
-- STUDENT_DEPT VARCHAR(20) NOT NULL
--    );

-- inserting values into the students table
INSERT INTO STUDENT VALUES(101, "Bhavitha", 125645, "CSEDS");
INSERT INTO STUDENT VALUES(102, "Nannu", 1891379, "CSE");
INSERT INTO STUDENT VALUES(103, "Manju", 7982478, "ECE");
INSERT INTO STUDENT VALUES(104, "Deepthi", 7982443, "EEE");
INSERT INTO STUDENT VALUES(105, "Sruthi", 84278737, "Civil");

SELECT * FROM RGM.STUDENT;
