-- creating table student in rgm database having attributes id, name, marks. 
CREATE TABLE STUDENT(
	SID INT PRIMARY KEY NOT NULL,
    SNAME VARCHAR(40) NOT NULL,
    SMARKS INT NOT NULL
    );
SELECT * FROM STUDENTS;
INSERT INTO STUDENTS VALUES (201,"ANU",87);
INSERT INTO STUDENTS VALUES (202,"RAGHAV",75);
INSERT INTO STUDENTS VALUES (203,"MODHAK",57);
INSERT INTO STUDENTS VALUES (204,"SRIHAN",68);
INSERT INTO STUDENTS VALUES (205,"RUPA",93);

SELECT * FROM STUDENTS WHERE SMARKS = 68;
SELECT * FROM STUDENTS WHERE SMARKS < 68;
SELECT * FROM STUDENTS WHERE SMARKS <= 68;
SELECT * FROM STUDENTS WHERE SMARKS >= 9068;
SELECT * FROM STUDENTS WHERE SMARKS != 68;
 SELECT * FROM STUDENTS WHERE SMARKS BETWEEN 60 AND 80; 
 SELECT * FROM STUDENTS WHERE SMARKS BETWEEN 60 AND 80 ORDER BY SMARKS;
SELECT * FROM STUDENTS WHERE SMARKS BETWEEN 60 AND 80 ORDER BY SNAME;
SELECT * FROM STUDENTS WHERE SMARKS BETWEEN 60 AND 80 ORDER BY SMARKS ASC;
SELECT * FROM STUDENTS WHERE SMARKS BETWEEN 60 AND 80 ORDER BY SMARKS DESC;
SELECT * FROM STUDENTS WHERE NOT SMARKS = 68;
SELECT DISTINCT  STD_ADDRESS FROM RGMLEARNERS;
SELECT COUNT(DISTINCT  STD_ADDRESS) FROM RGMLEARNERS;
SELECT COUNT(DISTINCT  STD_COLLEGE) FROM RGMLEARNERS;
SELECT * FROM STUDENTS;
SELECT * FROM RGMLEARNERS LIMIT 3;
SELECT * FROM RGMLEARNERS WHERE STD_ADDRESS = "HYDERABAD" LIMIT 2;
SELECT * FROM STUDENTS WHERE STD_ADDRESS = "HYDERABAD" LIMIT 0;
SELECT * FROM RGMLEARNERS WHERE STD_COLLEGE= "KGIT" ORDER BY STD_NAME LIMIT 2;

CREATE TABLE DOB (
	DATE_ DATE NOT NULL
    );
INSERT INTO DOB VALUES ( "2002-04-05");
SELECT * FROM DOB;