-- CREATE TABLE SALESMAN (
-- 	salesman_id INT PRIMARY KEY NOT NULL,
-- 	name_ VARCHAR(40) NOT NULL,
--     city VARCHAR(40) NOT NULL,
--     commission FLOAT NOT NULL
--     );
    
INSERT INTO SALESMAN VALUES (5001, "James Hong","New York", 0.15);
INSERT INTO SALESMAN VALUES (5002, "Nail Knite","Paris", 0.13);
INSERT INTO SALESMAN VALUES (5005, "Pit Alex","London", 0.11);
INSERT INTO SALESMAN VALUES (5006, "Mc Lyon","Paris", 0.14);
INSERT INTO SALESMAN VALUES (5007, "Paul Adam","Rome", 0.13);
INSERT INTO SALESMAN VALUES (5008, "Lauson Hen","Saint Jose", 0.15);

SELECT * FROM SALESMAN;

